[package]
name = "discord_data_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.2"
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = { version = "0.22.0", features = ["image"]}
image = { version = "0.24", features= ["jpeg", "png"] }
serde_json = "1.0.97"
